config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'cities#index'
  resources :cities
  resources :users, only: %i[show edit update destroy]

  ### Authorization routes
  get 'sign_up', to: 'authorization/registrations#new'
  post 'sign_up', to: 'authorization/registrations#create'
  get 'sign_in', to: 'authorization/sessions#new'
  post 'sign_in', to: 'authorization/sessions#create', as: 'log_in'
  delete 'logout', to: 'authorization/sessions#destroy'
  get 'password', to: 'authorization/passwords#edit', as: 'edit_password'
  patch 'password', to: 'authorization/passwords#update'
  get 'password/reset', to: 'authorization/password_resets#new'
  post 'password/reset', to: 'authorization/password_resets#create'
  get 'password/reset/edit', to: 'authorization/password_resets#edit'
  patch 'password/reset/edit', to: 'authorization/password_resets#update'
  ###
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  validates_presence_of :name, :country
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :cities
  
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: 'You must be signed in' if current_user.nil?
  end
end

app/controllers/authorization/password_resets_controller.rb
# frozen_string_literal: true

module Authorization
  class PasswordResetsController < ApplicationController
    def new; end

    def edit
      @user = User.find_signed!(password_params[:token], purpose: 'password_reset')
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
    end

    def create
      @user = User.find_by(email: password_params[:email])
      AuthMailer.with(user: @user).reset_password.deliver_now if @user.present?
      redirect_to root_path, notice: 'Please check your email to reset the password'
    end

    def update
      @user = User.find_signed!(password_params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in'
      else
        render :edit
      end
    end

    private

    def password_params
      params.require(:user).permit(:email, :token, :password, :password_confirmation)
    end
  end
end

app/controllers/authorization/passwords_controller.rb
# frozen_string_literal: true

module Authorization
  class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit; end

    def update
      if current_user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end

    private

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end
end

app/controllers/authorization/registrations_controller.rb
# frozen_string_literal: true

module Authorization
  class RegistrationsController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/authorization/sessions_controller.rb
# frozen_string_literal: true

module Authorization
  class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: :create

    def new; end

    def create
      user = User.find_by(email: user_params[:email])
      if user.present? && user.authenticate(user_params[:password])
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end

    private

    def user_params
      params.require(:user).permit(:password, :email)
    end
  end
end

app/controllers/base_controller.rb
# frozen_string_literal: true

class BaseController < ApplicationController
  before_action :require_user_logged_in!
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < BaseController
  before_action :find_city, only: %i[show edit update destroy]
  before_action :build_city, only: %i[new create]
  def index
    @cities = current_user.cities
  end

  def new; end

  def edit; end

  def show
    @weather = Weather::FetchWeather.new(@city).call
    @weather_body = @weather.body
  end

  def create
    @city.assign_attributes(city_params)
    if @city.save
      redirect_to city_path(@city)
    else
      render :edit
    end
  end

  def update
    @city.assign_attributes(city_params)
    if @city.save
      redirect_to city_path(@city)
    else
      render :edit
    end
  end

  def destroy
    @city.destroy
    redirect_to cities_path
  end

  private

  def city_params
    params.require(:city).permit(:country, :name)
  end

  def build_city
    @city = current_user.cities.new
  end

  def find_city
    @city = current_user.cities.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < BaseController
  def edit; end

  def update
    current_user.assign_attributes(user_params)
    if current_user.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    session[:user_id] = nil
    user = User.find(params[:id])
    user.destroy
    redirect_to sign_in_path
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/authorization/password_resets/edit.haml
.d-flex.w-100.justify-content-center.pt-4
  .flex-column.w-25
    %h1.pb-3
      Reset your password?
    = simple_form_for @user, url: password_reset_edit_path(token: params[:token]), html: {class: 'w-100'} do |f|
      .form-group
        = f.label 'password'
        = f.password_field :password, class: 'form-control'
      .form-group
        = f.label 'password_confirmation'
        = f.password_field :password_confirmation, class: 'form-control'
      .form-group.pt-3
        = f.submit 'Update', class: 'btn btn-dark'

app/views/authorization/password_resets/new.haml
.d-flex.w-100.justify-content-center.pt-4
  .flex-column.w-25
    %h1.pb-3
      Reset your password?
    = simple_form_for :user, url: password_reset_path, html: {class: 'w-100'} do |f|
      .form-group
        = f.input :email, input_html: {class: 'form-control'}
        = f.submit 'Reset Password'

app/views/cities/_form.haml
.d-flex.w-100.justify-content-center.pt-4
  .flex-column.w-25
    = simple_form_for @city, class:'form-control', html: {class: 'w-100'} do |f|
      .form-group
        = f.input :name, input_html: {class: 'form-control'}
      .form-group
        = f.input :country, input_html: {class: 'form-control'}
      .form-group
        = f.submit 'save'

app/views/cities/_weather_error.haml
.p-4
  =@weather_body.message.humanize
.d-flex.justify-content-center
  = image_tag('sad_cloud.png')

app/views/cities/_weather_info.haml
.d-flex.p-4
  .weather.pt-2.px-4
    %p
      %h4
        = "Weather:"
      -@weather_body.weather.each do |info|
        =image_tag("http://openweathermap.org/img/wn/#{info.icon}@2x.png")
        %p
          ="Overall weather: #{info.main}"
        %p
          = "description: #{info.description}"
  .temps.pt-2.px-4
    %p
      %h4
        = "Temperature:"
      %p
        ="Base Temp: #{@weather_body.main.temp}°C"
      %p
        = "min temperature: #{@weather_body.main.temp_min}°C"
      %p
        = "max temperature: #{@weather_body.main.temp_max}°C"
  .wind.pt-2.px-4
    %p
      %h4
        = "Wind:"
      %p
        = "Speed: #{@weather_body.wind.speed}km/h"
      %p
        = "Angle: #{@weather_body.wind.deg}°"

app/views/cities/edit.haml
.d-flex.w-100.justify-content-center.pt-4
  %h1
    = "Edit #{@city.name}"
= render 'form'

app/views/cities/index.haml
%table.table
  %thead
    %tr
      %th{scope: "col"}
        = link_to new_city_path, class: 'badge bg-dark text-decoration-none' do
          =inline_svg_tag 'icons/plus', width: '20px', height: '20px'
      %th{scope: "col"} Name
      %th{scope: "col"} Country
      %th{scope: "col"} Actions
  %tbody
    -@cities.all.each.with_index(1) do |city, index|
      %tr
        %th{scope: "row"}
          = index
        %td
          =city.name
        %td
          =city.country
        %td
          = link_to 'Edit', edit_city_path(city), class: 'btn btn-warning'
          = link_to 'Show', city_path(city), class: 'btn btn-dark'
          = link_to 'Destroy', city_path(city), method: :delete, class: 'btn btn-danger'

app/views/cities/new.haml
.d-flex.w-100.justify-content-center.pt-4
  %h1
    Add New City
= render 'form'

app/views/cities/show.haml
.p-4.d-flex.w-100.justify-content-between
  = "Weather for #{@city.name.capitalize}, #{@city.country.upcase}"
  = link_to 'Go Back', cities_path, class: 'btn btn-primary'
= render(@weather.fetched ? 'weather_info' : 'weather_error')

app/views/layouts/application.haml
<!DOCTYPE html>
%html
  %head
    %title
      ApploverTask

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/shared/navbar'
    = yield

app/views/layouts/shared/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.p-2
  %a.navbar-brand
    Weather App
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navbarNavDropdown.collapse.navbar-collapse.flex.justify-content-between
    .navbar-nav
      .nav-item
        = link_to 'Cities', cities_path, class: 'nav-link'
    .navbar-nav
      -if !current_user.present?
        .nav-item
          = link_to 'Sign in', sign_in_path, class: 'nav-link'
        .nav-item
          = link_to 'Sign up', sign_up_path, class: 'nav-link'
      -else
        .nav-item
          = link_to 'Profile', user_path(current_user), class: 'nav-link'
        .nav-item
          = link_to 'Logout', logout_path, class: 'nav-link', method: :delete

app/views/users/edit.haml
.d-flex.w-100.justify-content-center.pt-4
  = simple_form_for current_user, html: {class: 'w-25'} do |f|
    .form-group
      = f.label :email
      = f.text_field :email, class: 'form-control'
    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: 'form-control'
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: 'form-control'
    .form-group.pt-3
      = f.submit 'Save', class: 'btn btn-dark'

app/views/users/show.haml
.d-flex.w-100.justify-content-center
  .card{style: "width: 18rem;"}
    =image_tag 'profile.png', class:' card-img-top'
    .card-body
      %h5.card-title
        = "Email: #{current_user.email}"
      %p.card-text
        = "First Name: #{current_user.first_name}"
      %p.card-text
        = "Last Name: #{current_user.last_name}"
      = link_to 'Edit profile', edit_user_path, class: 'btn btn-warning'
      = link_to 'Delete profile', user_path(current_user), method: :delete, class: 'btn btn-danger'